[CmdletBinding()]
param([string]$Repository="$env:USERPROFILE\OneDrive\Documents\CERTIAURA\Repository\certiaura-knowledge-engine",[string]$Owner="ajc1786",[string]$RepositoryName="certiaura-knowledge-engine",[string]$ReportRoot="$env:USERPROFILE\OneDrive\Documents\CERTIAURA\Build_Reports\0055")
Set-StrictMode -Version Latest; $ErrorActionPreference="Stop"; $ExpectedSubject="Add Certiaura Build 0055 historical GitHub Actions evidence reconciliation, retatrutide baseline closure, reusable architecture handoff and governed next-peptide transition baseline"
function Assert-Exit([string]$Name){if($LASTEXITCODE -ne 0){throw "$Name failed with exit code $LASTEXITCODE."}}
$Head=(git -C $Repository rev-parse HEAD).Trim(); Assert-Exit "read HEAD"; $Subject=(git -C $Repository log -1 --format=%s).Trim(); Assert-Exit "read subject"; if($Subject -ne $ExpectedSubject){throw "Build 0055 commit subject mismatch."}
$HistoricalSummaryPath=Join-Path $Repository "Documentation\Build_Records\0055\HISTORICAL_GITHUB_ACTIONS_AUDIT_SUMMARY.json"; if(-not(Test-Path -LiteralPath $HistoricalSummaryPath -PathType Leaf)){throw "Historical GitHub Actions audit summary is missing."}; $HistoricalSummary=Get-Content -LiteralPath $HistoricalSummaryPath -Raw|ConvertFrom-Json; if([string]$HistoricalSummary.result -ne "HISTORICAL_ACTIONS_AUDIT_COMPLETE" -or -not [bool]$HistoricalSummary.all_builds_accounted -or [int]$HistoricalSummary.unresolved_count -ne 0 -or [int]$HistoricalSummary.accounted_count -ne 54){throw "Historical GitHub Actions accounting is incomplete."}
git -C $Repository fetch origin main --quiet; Assert-Exit "fetch origin/main"; $Remote=(git -C $Repository rev-parse origin/main).Trim(); Assert-Exit "read origin/main"; if($Head -ne $Remote){throw "Local HEAD does not equal origin/main."}; $Dirty=@(git -C $Repository status --porcelain --untracked-files=all); Assert-Exit "read status"; if($Dirty.Count -ne 0){throw "Repository is not clean."}
$Headers=@{Accept="application/vnd.github+json";"User-Agent"="Certiaura-Build-Closure";"X-GitHub-Api-Version"="2022-11-28"}; $Uri=("https://api.github.com/repos/{0}/{1}/actions/runs?head_sha={2}&per_page=100" -f $Owner,$RepositoryName,$Head); $Response=Invoke-RestMethod -Uri $Uri -Headers $Headers -Method Get; $Runs=@($Response.workflow_runs|Where-Object {$_.head_sha -eq $Head}|Sort-Object created_at -Descending); if($Runs.Count -lt 1){throw "No GitHub Actions run found for canonical Build 0055 commit."}; $Run=$Runs[0]; if($Run.status -ne "completed" -or $Run.conclusion -ne "success"){throw "GitHub Actions is not green."}; if(-not $Run.id){throw "GitHub Actions run ID is missing."}
New-Item -ItemType Directory -Path $ReportRoot -Force|Out-Null; $Evidence=[ordered]@{build_number="0055";canonical_commit=$Head;commit_subject=$Subject;run_id=[string]$Run.id;workflow_name=[string]$Run.name;status=[string]$Run.status;conclusion=[string]$Run.conclusion;run_attempt=[int]$Run.run_attempt;branch=[string]$Run.head_branch;event=[string]$Run.event;created_at=[string]$Run.created_at;updated_at=[string]$Run.updated_at;local_head=$Head;origin_main=$Remote;repository_clean=$true;historical_actions_accounted_count=[int]$HistoricalSummary.accounted_count;historical_actions_verified_run_id_count=[int]$HistoricalSummary.verified_run_id_count;historical_actions_exception_count=[int]$HistoricalSummary.exception_count;historical_actions_all_exact_run_ids_captured=[bool]$HistoricalSummary.all_exact_run_ids_captured;founder_phrase_required="GREEN"}; $Path=Join-Path $ReportRoot "BUILD_0055_GITHUB_ACTIONS_GREEN.json"; $Evidence|ConvertTo-Json -Depth 8|Set-Content -LiteralPath $Path -Encoding UTF8; Write-Host ""; Write-Host "BUILD_0055_GITHUB_ACTIONS_GREEN" -ForegroundColor Green; Write-Host "Run ID:"; Write-Host $Run.id; Write-Host "Canonical commit:"; Write-Host $Head; Write-Host "Evidence report:"; Write-Host $Path
