from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path

BUILD_MARKER_START = "<!-- CERTIAURA_BUILD_0053_CHECKPOINT_START -->"
BUILD_MARKER_END = "<!-- CERTIAURA_BUILD_0053_CHECKPOINT_END -->"
LESSON_MARKER_START = "<!-- CERTIAURA_BUILD_0053_LESSONS_START -->"
LESSON_MARKER_END = "<!-- CERTIAURA_BUILD_0053_LESSONS_END -->"


def append_block(path: Path, start: str, end: str, block: str) -> None:
    text = path.read_text(encoding="utf-8") if path.exists() else ""
    if start in text:
        before = text.split(start, 1)[0].rstrip()
        parts = text.split(end, 1)
        after = parts[1].lstrip() if len(parts) == 2 else ""
        text = before + "\n\n" + block.rstrip() + "\n"
        if after:
            text += "\n" + after
    else:
        text = text.rstrip() + "\n\n" + block.rstrip() + "\n"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")


def update(repository: str | Path) -> list[str]:
    repo = Path(repository)
    continuity = (
        repo / "00_Governance/CERTIAURA_LOCKED_BUILD_CONTINUITY_AND_CHECKPOINT.md"
    )
    lessons = (
        repo
        / "00_Governance/CERTIAURA_LOCKED_ACCUMULATED_LESSONS_AND_CONTINUOUS_LEARNING_STANDARD.md"
    )
    control = (
        repo
        / "00_Governance/CERTIAURA_LOCKED_ACCUMULATED_LESSONS_AND_CONTINUOUS_LEARNING_STANDARD.control.json"
    )

    checkpoint = f"""{BUILD_MARKER_START}
## Build 0053 continuation checkpoint - generated by controlled import

- Last closed build: `0052` (`ACTIONS_GREEN_CLOSED`)
- Closed predecessor commit: `890df218b4f4dea92f4ccfa36b8106de59eca1b1`
- Current build: `0053` candidate `RC4`
- Build title: `retatrutide governed knowledge change implementation, cross-asset impact control, controlled publication and post-change effectiveness surveillance baseline`
- Current state after import: `REPOSITORY_VALIDATED` pending exact commit, push, GitHub Actions and founder `GREEN`
- Prohibited Build 0052 predecessor candidates: `RC1-RC5`
- Withdrawn and prohibited Build 0053 candidates: `RC1`, `RC2`, `RC3`
- Required next action: commit using the reserved subject, push, verify GitHub Actions, then obtain founder `GREEN`
- Proposed following action: Build 0054 Retatrutide end-to-end operational assurance and Platinum readiness assessment

{BUILD_MARKER_END}"""

    lesson_block = f"""{LESSON_MARKER_START}
### CERT-LESSON-0053-001 - Governed knowledge changes require complete cross-surface propagation

**Origin build:** 0053
**Status:** LOCKED_ACTIVE
**Defect or risk:** An approved scientific or monitoring change can leave stale reports, interfaces or artificial-intelligence responses live.
**Preventive control:** Require an exact approved expected-target set and block implementation unless the applied-target set is identical.
**Executable regression:** Deliberately defective partial-propagation example must fail.
**Release gate:** `CONTROLLED_PROPAGATION_VALIDATED`

### CERT-LESSON-0053-002 - Publication and effectiveness evidence are separate closure gates

**Origin build:** 0053
**Status:** LOCKED_ACTIVE
**Defect or risk:** Publication can be mistaken for effective implementation.
**Preventive control:** Require approved implementation before publication and a later evidence-linked effectiveness review before close/watch/reopen.
**Executable regression:** Publication-before-approval and effectiveness-without-evidence examples must fail.
**Release gate:** `POST_CHANGE_EFFECTIVENESS_VALIDATED`

### CERT-LESSON-0053-003 - Synthetic predecessor fixtures must reproduce canonical register topology

**Origin build:** 0053 RC2
**Status:** LOCKED_ACTIVE
**Defect or risk:** A synthetic fixture can invent Master Asset Register rows for predecessor governance files and conceal a real-world import failure.
**Preventive control:** Derive predecessor files from canonical Git and reproduce the canonical formal-asset registration topology; do not add fixture rows merely to satisfy UPDATE reconciliation.
**Executable regression:** Governance predecessor files must exist while remaining absent from the synthetic Master Asset Register; forced rollback and clean reapply must both pass.
**Release gate:** `CANONICAL_REGISTER_TOPOLOGY_REGRESSION_VALIDATED`

### CERT-LESSON-0053-004 - Runtime-generated text must declare byte-stable newline policy

**Origin build:** 0053 RC3
**Status:** LOCKED_ACTIVE
**Defect or risk:** Python text writers using platform-default newline translation can create CRLF working-tree bytes that Git normalises to LF in the index, failing exact staged-byte equality on Windows.
**Preventive control:** Every production `Path.write_text` call must declare `newline="\n"`; runtime-generated reports must remain LF byte-stable before and after staging.
**Executable regression:** An AST audit rejects any production Python `write_text` call without an explicit LF newline argument, and the Windows PowerShell 5.1 temporary-clone staged-byte gate must pass.
**Release gate:** `WINDOWS_RUNTIME_TEXT_BYTE_STABILITY_VALIDATED`

### CERT-LESSON-0053-005 - Full owned-scope tests must pass before canonical apply

**Origin build:** 0053 RC4
**Status:** LOCKED_ACTIVE
**Defect or risk:** A temporary-clone regression can pass while later canonical tests fail if those tests are omitted before apply or scan unrelated historical repository content.
**Preventive control:** Scope every Build 0053 test to Asset Intent Manifest ownership, run the complete repository validator and Build 0053 test suite in the temporary clone before canonical apply, and automatically restore the transaction backup after any later gate failure.
**Executable regression:** The temporary clone must return `BUILD_0053_PRE_CANONICAL_FULL_SUITE_VALIDATED`; staged post-import rollback must return `ROLLBACK_STATE_EXACT` and a clean predecessor HEAD.
**Release gate:** `PRE_CANONICAL_FULL_SUITE_AND_AUTOMATIC_ROLLBACK_VALIDATED`

{LESSON_MARKER_END}"""

    append_block(
        continuity, BUILD_MARKER_START, BUILD_MARKER_END, checkpoint
    )
    append_block(lessons, LESSON_MARKER_START, LESSON_MARKER_END, lesson_block)

    if control.exists():
        data = json.loads(control.read_text(encoding="utf-8"))
    else:
        data = {}
    updates = data.setdefault("build_updates", [])
    updates = [
        item for item in updates if str(item.get("build_number")) != "0053"
    ]
    updates.append(
        {
            "build_number": "0053",
            "status": "REPOSITORY_VALIDATED_PENDING_CLOSURE",
            "updated_at": datetime.now(timezone.utc).isoformat(),
            "release_gates": [
                "CONTROLLED_PROPAGATION_VALIDATED",
                "POST_CHANGE_EFFECTIVENESS_VALIDATED",
                "CANONICAL_REGISTER_TOPOLOGY_REGRESSION_VALIDATED",
                "WINDOWS_RUNTIME_TEXT_BYTE_STABILITY_VALIDATED",
                "PRE_CANONICAL_FULL_SUITE_AND_AUTOMATIC_ROLLBACK_VALIDATED",
            ],
            "lesson_ids": [
                "CERT-LESSON-0053-001",
                "CERT-LESSON-0053-002",
                "CERT-LESSON-0053-003",
                "CERT-LESSON-0053-004",
                "CERT-LESSON-0053-005",
            ],
        }
    )
    data["build_updates"] = updates
    control.parent.mkdir(parents=True, exist_ok=True)
    control.write_text(
        json.dumps(data, indent=2) + "\n", encoding="utf-8", newline="\n"
    )

    return [
        str(continuity.relative_to(repo)).replace("\\", "/"),
        str(lessons.relative_to(repo)).replace("\\", "/"),
        str(control.relative_to(repo)).replace("\\", "/"),
    ]


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("repository")
    args = parser.parse_args()
    print(json.dumps({"updated": update(args.repository)}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
