from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path

START = "<!-- CERTIAURA_BUILD_0056_CHECKPOINT_START -->"
END = "<!-- CERTIAURA_BUILD_0056_CHECKPOINT_END -->"
LESSONS_START = "<!-- CERTIAURA_BUILD_0056_LESSONS_START -->"
LESSONS_END = "<!-- CERTIAURA_BUILD_0056_LESSONS_END -->"


def append_control(path, start, end, block):
    text = path.read_text(encoding="utf-8") if path.exists() else ""
    if start in text:
        before = text.split(start, 1)[0].rstrip()
        after = text.split(end, 1)[1].lstrip() if end in text else ""
        text = before + "\n\n" + block.rstrip() + "\n" + ("\n" + after if after else "")
    else:
        text = text.rstrip() + "\n\n" + block.rstrip() + "\n"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")


def update(repository):
    repo = Path(repository)
    continuity = repo / "00_Governance/CERTIAURA_LOCKED_BUILD_CONTINUITY_AND_CHECKPOINT.md"
    lessons = repo / "00_Governance/CERTIAURA_LOCKED_ACCUMULATED_LESSONS_AND_CONTINUOUS_LEARNING_STANDARD.md"
    control = repo / "00_Governance/CERTIAURA_LOCKED_ACCUMULATED_LESSONS_AND_CONTINUOUS_LEARNING_STANDARD.control.json"

    checkpoint = f"""{START}
## Build 0056 continuation checkpoint - generated by controlled import

- Last closed build: `0055` (`ACTIONS_GREEN_CLOSED`)
- Canonical predecessor commit: `977829a987baf744beab4762478d9f0a88165fb0`
- Predecessor GitHub Actions run ID: `29997204286` (`completed`, `success`, attempt 1)
- Historical Actions baseline: Builds 0001-0054 fully accounted, 53 exact run IDs and one controlled Build 0001 exception
- Current build: `0056` candidate `RC1`
- Build title: `tesamorelin evidence corpus mapping, biological and safety boundary definition, target-specific data contracts, monitoring model and controlled pilot acceptance baseline`
- State after import: `REPOSITORY_VALIDATED` pending canonical commit, push, exact Actions run ID and founder `GREEN`
- Pilot boundary: Tesamorelin knowledge-architecture work only; no clinical recommendation, dosing, diagnosis or prescribing authority

{END}"""

    lesson_block = f"""{LESSONS_START}
### CERT-LESSON-0056-001 - Target-peptide evidence must be mapped independently of predecessor peptide claims
### CERT-LESSON-0056-002 - Biological boundaries require explicit contexts, exclusions and uncertainties
### CERT-LESSON-0056-003 - Safety boundaries require stop, hold, escalation and emergency routes
### CERT-LESSON-0056-004 - Monitoring models must prohibit autonomous clinical clearance and dosing decisions
### CERT-LESSON-0056-005 - Controlled pilot acceptance requires zero critical gaps and human approval
### CERT-LESSON-0056-006 - Evidence gaps cannot close automatically or without traceable evidence
### CERT-LESSON-0056-007 - Staged-byte reports must derive the build number from the current manifest
### CERT-LESSON-0056-008 - Exact GitHub Actions run ID remains mandatory for canonical closure

{LESSONS_END}"""

    append_control(continuity, START, END, checkpoint)
    append_control(lessons, LESSONS_START, LESSONS_END, lesson_block)

    data = json.loads(control.read_text(encoding="utf-8")) if control.exists() else {}
    updates = [item for item in data.setdefault("build_updates", []) if str(item.get("build_number")) != "0056"]
    updates.append({
        "build_number": "0056",
        "status": "REPOSITORY_VALIDATED_PENDING_CLOSURE",
        "updated_at": datetime.now(timezone.utc).isoformat(),
        "release_gates": [
            "TESAMORELIN_EVIDENCE_CORPUS_VALIDATED",
            "TESAMORELIN_BIOLOGICAL_BOUNDARY_VALIDATED",
            "TESAMORELIN_SAFETY_BOUNDARY_VALIDATED",
            "TESAMORELIN_MONITORING_MODEL_VALIDATED",
            "TESAMORELIN_CONTROLLED_PILOT_ACCEPTANCE_VALIDATED",
            "TESAMORELIN_EVIDENCE_GAP_CONTROL_VALIDATED",
            "STAGED_BYTE_BUILD_NUMBER_DERIVATION_VALIDATED",
            "GITHUB_ACTIONS_RUN_ID_EVIDENCE_REQUIRED"
        ],
        "lesson_ids": [
            "CERT-LESSON-0056-001", "CERT-LESSON-0056-002", "CERT-LESSON-0056-003",
            "CERT-LESSON-0056-004", "CERT-LESSON-0056-005", "CERT-LESSON-0056-006",
            "CERT-LESSON-0056-007", "CERT-LESSON-0056-008"
        ]
    })
    data["build_updates"] = updates
    control.parent.mkdir(parents=True, exist_ok=True)
    control.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8", newline="\n")
    return [str(path.relative_to(repo)).replace("\\", "/") for path in (continuity, lessons, control)]


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("repository")
    args = parser.parse_args()
    print(json.dumps({"updated": update(args.repository)}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
