from __future__ import annotations
import argparse,json
from datetime import datetime,timezone
from pathlib import Path
START="<!-- CERTIAURA_BUILD_0057_CHECKPOINT_START -->"; END="<!-- CERTIAURA_BUILD_0057_CHECKPOINT_END -->"; LS="<!-- CERTIAURA_BUILD_0057_LESSONS_START -->"; LE="<!-- CERTIAURA_BUILD_0057_LESSONS_END -->"
def append(path,start,end,block):
 text=path.read_text(encoding="utf-8") if path.exists() else ""
 if start in text:
  before=text.split(start,1)[0].rstrip(); after=text.split(end,1)[1].lstrip() if end in text else ""; text=before+"\n\n"+block.rstrip()+"\n"+("\n"+after if after else "")
 else: text=text.rstrip()+"\n\n"+block.rstrip()+"\n"
 path.parent.mkdir(parents=True,exist_ok=True); path.write_text(text,encoding="utf-8",newline="\n")
def update(repository):
 repo=Path(repository); c=repo/"00_Governance/CERTIAURA_LOCKED_BUILD_CONTINUITY_AND_CHECKPOINT.md"; l=repo/"00_Governance/CERTIAURA_LOCKED_ACCUMULATED_LESSONS_AND_CONTINUOUS_LEARNING_STANDARD.md"; j=repo/"00_Governance/CERTIAURA_LOCKED_ACCUMULATED_LESSONS_AND_CONTINUOUS_LEARNING_STANDARD.control.json"
 checkpoint=f'''{START}
## Build 0057 continuation checkpoint - generated by controlled import

- Last closed build: `0056` (`ACTIONS_GREEN_CLOSED`)
- Canonical predecessor commit: `2e6fe434bf1d0566bf3d1afa33bae24ce13b3b44`
- Predecessor GitHub Actions run ID: `29999430792` (`completed`, `success`, attempt 1)
- Current build: `0057` candidate `RC1`
- Build title: `tesamorelin governed evidence ingestion, provenance validation, monitoring workflow simulation, safety escalation, audit replay and controlled acceptance baseline`
- State after import: `REPOSITORY_VALIDATED` pending canonical commit, push, exact Actions run ID and founder `GREEN`
- Clinical boundary: governed knowledge-workflow simulation only
- Git control: automatic GC and maintenance prompts prohibited during commit, push and closure

{END}'''
 lessons=f'''{LS}
### CERT-LESSON-0057-001 - Evidence ingestion requires immutable provenance identifiers and source hashes
### CERT-LESSON-0057-002 - Monitoring workflow simulation must route safety signals to stop and escalation
### CERT-LESSON-0057-003 - Accepted simulation requires complete deterministic audit replay
### CERT-LESSON-0057-004 - Critical gaps and unresolved safety signals block acceptance
### CERT-LESSON-0057-005 - Simulation remains non-clinical and cannot authorise dosing, diagnosis, prescribing or treatment
### CERT-LESSON-0057-006 - Canonical Git operations must disable automatic maintenance non-interactively and restore prior config
### CERT-LESSON-0057-007 - Locked object-directory prompts must never require repeated operator responses
### CERT-LESSON-0057-008 - Exact GitHub Actions run ID remains mandatory before closure

{LE}'''
 append(c,START,END,checkpoint); append(l,LS,LE,lessons); data=json.loads(j.read_text(encoding="utf-8")) if j.exists() else {}; ups=[x for x in data.setdefault("build_updates",[]) if str(x.get("build_number"))!="0057"]
 ups.append({"build_number":"0057","status":"REPOSITORY_VALIDATED_PENDING_CLOSURE","updated_at":datetime.now(timezone.utc).isoformat(),"release_gates":["TESAMORELIN_EVIDENCE_INGESTION_VALIDATED","TESAMORELIN_MONITORING_WORKFLOW_SIMULATION_VALIDATED","TESAMORELIN_SAFETY_ESCALATION_VALIDATED","TESAMORELIN_AUDIT_REPLAY_VALIDATED","TESAMORELIN_SIMULATION_ACCEPTANCE_VALIDATED","NON_INTERACTIVE_GIT_GUARD_VALIDATED","GITHUB_ACTIONS_RUN_ID_EVIDENCE_REQUIRED"],"lesson_ids":[f"CERT-LESSON-0057-{i:03d}" for i in range(1,9)]}); data["build_updates"]=ups; j.write_text(json.dumps(data,indent=2)+"\n",encoding="utf-8",newline="\n"); return [str(x.relative_to(repo)).replace("\\","/") for x in (c,l,j)]
def main():
 p=argparse.ArgumentParser(); p.add_argument("repository"); a=p.parse_args(); print(json.dumps({"updated":update(a.repository)},indent=2)); return 0
if __name__=="__main__": raise SystemExit(main())
