from __future__ import annotations
import argparse,json
from datetime import datetime,timezone
from pathlib import Path
START="<!-- CERTIAURA_BUILD_0054_CHECKPOINT_START -->"; END="<!-- CERTIAURA_BUILD_0054_CHECKPOINT_END -->"; LS="<!-- CERTIAURA_BUILD_0054_LESSONS_START -->"; LE="<!-- CERTIAURA_BUILD_0054_LESSONS_END -->"
def append(path,start,end,block):
 text=path.read_text(encoding="utf-8") if path.exists() else ""
 if start in text:
  before=text.split(start,1)[0].rstrip(); after=text.split(end,1)[1].lstrip() if end in text else ""; text=before+"\n\n"+block.rstrip()+"\n"+("\n"+after if after else "")
 else: text=text.rstrip()+"\n\n"+block.rstrip()+"\n"
 path.parent.mkdir(parents=True,exist_ok=True); path.write_text(text,encoding="utf-8",newline="\n")
def update(repository):
 repo=Path(repository); continuity=repo/"00_Governance/CERTIAURA_LOCKED_BUILD_CONTINUITY_AND_CHECKPOINT.md"; lessons=repo/"00_Governance/CERTIAURA_LOCKED_ACCUMULATED_LESSONS_AND_CONTINUOUS_LEARNING_STANDARD.md"; control=repo/"00_Governance/CERTIAURA_LOCKED_ACCUMULATED_LESSONS_AND_CONTINUOUS_LEARNING_STANDARD.control.json"
 checkpoint=f"""{START}
## Build 0054 continuation checkpoint - generated by controlled import

- Last closed build: `0053` (`ACTIONS_GREEN_CLOSED`)
- Canonical predecessor commit: `d5b7b84a2c543bbdd5cad8727f1c9005c27ca70d`
- Predecessor GitHub Actions run ID: `29986875639` (`completed`, `success`, attempt 1)
- Current build: `0054` candidate `RC4`
- Build title: `retatrutide end-to-end operational assurance, controlled release readiness, failure-mode coverage and Platinum readiness assessment baseline`
- State after import: `REPOSITORY_VALIDATED` pending commit, push, exact Actions run ID and founder `GREEN`
- Closure prohibition: do not mark `ACTIONS_GREEN_CLOSED` without an Actions run ID tied to the canonical commit

{END}"""
 lesson=f"""{LS}
### CERT-LESSON-0054-001 - End-to-end assurance is distinct from component validation
### CERT-LESSON-0054-002 - Failure modes require detection, containment, rollback and executable evidence
### CERT-LESSON-0054-003 - Critical gaps override Platinum readiness scores
### CERT-LESSON-0054-004 - Architecture reuse requires an explicit boundary decision
### CERT-LESSON-0054-005 - GitHub Actions run ID is mandatory closure evidence
### CERT-LESSON-0054-006 - Intentional predecessor-path reuse requires explicit approved UPDATE classification
### CERT-LESSON-0054-007 - Approved byte-identical updates are owned no-ops, not mandatory staged changes
### CERT-LESSON-0054-008 - Optional manifest properties require StrictMode-safe PSObject.Properties access

A founder `GREEN` cannot substitute for the exact successful Actions run tied to the canonical commit.

{LE}"""
 append(continuity,START,END,checkpoint); append(lessons,LS,LE,lesson)
 data=json.loads(control.read_text(encoding="utf-8")) if control.exists() else {}; updates=[x for x in data.setdefault("build_updates",[]) if str(x.get("build_number"))!="0054"]; updates.append({"build_number":"0054","status":"REPOSITORY_VALIDATED_PENDING_CLOSURE","updated_at":datetime.now(timezone.utc).isoformat(),"release_gates":["END_TO_END_OPERATIONAL_ASSURANCE_VALIDATED","FAILURE_MODE_COVERAGE_VALIDATED","PLATINUM_CRITICAL_GAP_OVERRIDE_VALIDATED","ARCHITECTURE_REUSE_BOUNDARY_VALIDATED","GITHUB_ACTIONS_RUN_ID_EVIDENCE_REQUIRED","PREDECESSOR_REUSED_PATH_CLASSIFICATION_VALIDATED","NO_OP_UPDATE_STAGED_CHANGESET_VALIDATED","OPTIONAL_MANIFEST_PROPERTY_STRICTMODE_VALIDATED"],"lesson_ids":["CERT-LESSON-0054-001","CERT-LESSON-0054-002","CERT-LESSON-0054-003","CERT-LESSON-0054-004","CERT-LESSON-0054-005","CERT-LESSON-0054-006","CERT-LESSON-0054-007","CERT-LESSON-0054-008"]}); data["build_updates"]=updates; control.parent.mkdir(parents=True,exist_ok=True); control.write_text(json.dumps(data,indent=2)+"\n",encoding="utf-8",newline="\n")
 return [str(x.relative_to(repo)).replace("\\","/") for x in (continuity,lessons,control)]
def main():
 p=argparse.ArgumentParser(); p.add_argument("repository"); a=p.parse_args(); print(json.dumps({"updated":update(a.repository)},indent=2)); return 0
if __name__=="__main__": raise SystemExit(main())
