from __future__ import annotations
import argparse,json
from datetime import datetime,timezone
from pathlib import Path
START="<!-- CERTIAURA_BUILD_0055_CHECKPOINT_START -->"; END="<!-- CERTIAURA_BUILD_0055_CHECKPOINT_END -->"; LS="<!-- CERTIAURA_BUILD_0055_LESSONS_START -->"; LE="<!-- CERTIAURA_BUILD_0055_LESSONS_END -->"
def append(path,start,end,block):
 text=path.read_text(encoding="utf-8") if path.exists() else ""
 if start in text:
  before=text.split(start,1)[0].rstrip(); after=text.split(end,1)[1].lstrip() if end in text else ""; text=before+"\n\n"+block.rstrip()+"\n"+("\n"+after if after else "")
 else: text=text.rstrip()+"\n\n"+block.rstrip()+"\n"
 path.parent.mkdir(parents=True,exist_ok=True); path.write_text(text,encoding="utf-8",newline="\n")
def update(repository):
 repo=Path(repository); continuity=repo/"00_Governance/CERTIAURA_LOCKED_BUILD_CONTINUITY_AND_CHECKPOINT.md"; lessons=repo/"00_Governance/CERTIAURA_LOCKED_ACCUMULATED_LESSONS_AND_CONTINUOUS_LEARNING_STANDARD.md"; control=repo/"00_Governance/CERTIAURA_LOCKED_ACCUMULATED_LESSONS_AND_CONTINUOUS_LEARNING_STANDARD.control.json"
 checkpoint=f"""{START}
## Build 0055 continuation checkpoint - generated by controlled import

- Last closed build: `0054` (`ACTIONS_GREEN_CLOSED`)
- Canonical predecessor commit: `8a9dba6615448c1ad85c44cdf89269a8fc3e00e8`
- Predecessor GitHub Actions run ID: `29993394313` (`completed`, `success`, attempt 1)
- Current build: `0055` candidate `RC2`
- Build title: `historical GitHub Actions evidence reconciliation, retatrutide baseline closure, reusable architecture handoff and governed next-peptide transition baseline`
- State after import: `REPOSITORY_VALIDATED` pending canonical commit, push, exact Actions run ID and founder `GREEN`
- Retatrutide boundary: operational knowledge baseline closure is not clinical or regulatory approval

{END}"""
 lesson=f"""{LS}
### CERT-LESSON-0055-001 - Baseline closure requires explicit scope and evidenced zero-critical-gap status
### CERT-LESSON-0055-002 - Controlled knowledge release must not be represented as clinical authorisation
### CERT-LESSON-0055-003 - Reusable architecture excludes peptide-specific clinical content by default
### CERT-LESSON-0055-004 - Next-peptide selection requires target-specific evidence and safety boundaries
### CERT-LESSON-0055-005 - Closed baselines require governed exception and reopening controls
### CERT-LESSON-0055-006 - Canonical closure evidence includes the exact successful GitHub Actions run ID
### CERT-LESSON-0055-007 - Current-build tests use exact Asset Intent Manifest paths
### CERT-LESSON-0055-008 - Historical Actions evidence requires repository-wide reconciliation
### CERT-LESSON-0055-009 - Backfilled evidence must be distinguished from contemporaneous capture
### CERT-LESSON-0055-010 - Builds 0001-0054 require complete accounting before Build 0055 closure

{LE}"""
 append(continuity,START,END,checkpoint); append(lessons,LS,LE,lesson)
 data=json.loads(control.read_text(encoding="utf-8")) if control.exists() else {}; updates=[x for x in data.setdefault("build_updates",[]) if str(x.get("build_number"))!="0055"]; updates.append({"build_number":"0055","status":"REPOSITORY_VALIDATED_PENDING_CLOSURE","updated_at":datetime.now(timezone.utc).isoformat(),"release_gates":["RETATRUTIDE_BASELINE_CLOSURE_VALIDATED","CONTROLLED_KNOWLEDGE_RELEASE_BOUNDARY_VALIDATED","ARCHITECTURE_HANDOFF_BOUNDARY_VALIDATED","NEXT_PEPTIDE_PILOT_SELECTION_VALIDATED","BASELINE_EXCEPTION_REOPENING_VALIDATED","GITHUB_ACTIONS_RUN_ID_EVIDENCE_REQUIRED","CURRENT_BUILD_MANIFEST_SCOPED_TESTS_VALIDATED","HISTORICAL_ACTIONS_EVIDENCE_RECONCILED","HISTORICAL_ACTIONS_CAPTURE_PROVENANCE_CLASSIFIED","HISTORICAL_ACTIONS_ALL_BUILDS_ACCOUNTED"],"lesson_ids":["CERT-LESSON-0055-001","CERT-LESSON-0055-002","CERT-LESSON-0055-003","CERT-LESSON-0055-004","CERT-LESSON-0055-005","CERT-LESSON-0055-006","CERT-LESSON-0055-007","CERT-LESSON-0055-008","CERT-LESSON-0055-009","CERT-LESSON-0055-010"]}); data["build_updates"]=updates; control.parent.mkdir(parents=True,exist_ok=True); control.write_text(json.dumps(data,indent=2)+"\n",encoding="utf-8",newline="\n")
 return [str(x.relative_to(repo)).replace("\\","/") for x in (continuity,lessons,control)]
def main():
 p=argparse.ArgumentParser(); p.add_argument("repository"); a=p.parse_args(); print(json.dumps({"updated":update(a.repository)},indent=2)); return 0
if __name__=="__main__": raise SystemExit(main())
